# Generated by Django 4.0.7 on 2022-09-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("freight", "0001_squashed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contracthandler",
            name="last_error",
            field=models.IntegerField(
                choices=[
                    (0, "No error"),
                    (1, "Invalid token"),
                    (2, "Expired token"),
                    (3, "Insufficient permissions"),
                    (4, "No character set for fetching alliance contacts"),
                    (5, "ESI API is currently unavailable"),
                    (6, "Operation mode does not match with current setting"),
                    (99, "Unknown error"),
                ],
                default=0,
                help_text="error that occurred at the last sync attempt (if any)",
            ),
        ),
    ]
